# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mpauw <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/08 11:06:44 by mpauw             #+#    #+#              #
#    Updated: 2017/11/13 10:59:15 by mpauw            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CPATH = ./
SRC = $(CPATH)ft_atoi.c\
	  $(CPATH)ft_bzero.c\
	  $(CPATH)ft_isalnum.c\
	  $(CPATH)ft_isalpha.c\
	  $(CPATH)ft_isascii.c\
	  $(CPATH)ft_isdigit.c\
	  $(CPATH)ft_isprint.c\
	  $(CPATH)ft_itoa.c\
	  $(CPATH)ft_memalloc.c\
	  $(CPATH)ft_memccpy.c\
	  $(CPATH)ft_memchr.c\
	  $(CPATH)ft_memcmp.c\
	  $(CPATH)ft_memcpy.c\
	  $(CPATH)ft_memdel.c\
	  $(CPATH)ft_memmove.c\
	  $(CPATH)ft_memset.c\
	  $(CPATH)ft_putchar.c\
	  $(CPATH)ft_putchar_fd.c\
	  $(CPATH)ft_putendl.c\
	  $(CPATH)ft_putendl_fd.c\
	  $(CPATH)ft_putnbr.c\
	  $(CPATH)ft_putnbr_fd.c\
	  $(CPATH)ft_putstr.c\
	  $(CPATH)ft_putstr_fd.c\
	  $(CPATH)ft_strcat.c\
	  $(CPATH)ft_strchr.c\
	  $(CPATH)ft_strclr.c\
	  $(CPATH)ft_strcmp.c\
	  $(CPATH)ft_strcpy.c\
	  $(CPATH)ft_strdel.c\
	  $(CPATH)ft_strdup.c\
	  $(CPATH)ft_strequ.c\
	  $(CPATH)ft_striter.c\
	  $(CPATH)ft_striteri.c\
	  $(CPATH)ft_strjoin.c\
	  $(CPATH)ft_strlcat.c\
	  $(CPATH)ft_strlen.c\
	  $(CPATH)ft_strmap.c\
	  $(CPATH)ft_strmapi.c\
	  $(CPATH)ft_strncat.c\
	  $(CPATH)ft_strncmp.c\
	  $(CPATH)ft_strncpy.c\
	  $(CPATH)ft_strnequ.c\
	  $(CPATH)ft_strnew.c\
	  $(CPATH)ft_strnstr.c\
	  $(CPATH)ft_strrchr.c\
	  $(CPATH)ft_strsplit.c\
	  $(CPATH)ft_strstr.c\
	  $(CPATH)ft_strsub.c\
	  $(CPATH)ft_strtrim.c\
	  $(CPATH)ft_tolower.c\
	  $(CPATH)ft_toupper.c\
	  $(CPATH)ft_lstnew.c\
	  $(CPATH)ft_lstdelone.c\
	  $(CPATH)ft_lstdel.c\
	  $(CPATH)ft_lstadd.c\
	  $(CPATH)ft_lstiter.c\
	  $(CPATH)ft_lstmap.c\
	  $(CPATH)ft_numlen.c\
	  $(CPATH)ft_lstaddnewr.c\
	  $(CPATH)ft_lstaddnewl.c\
	  $(CPATH)ft_lstaddright.c\
	  $(CPATH)ft_power.c\
	  $(CPATH)ft_factorial.c\
	  $(CPATH)ft_sqrt.c\
	  $(CPATH)ft_next_prime.c\
	  $(CPATH)ft_factorization.c\
	  $(CPATH)ft_isprime.c\
	  $(CPATH)ft_convert_base.c
POINTO = ft_atoi.o\
		 ft_bzero.o\
		 ft_isalnum.o\
		 ft_isalpha.o\
		 ft_isascii.o\
		 ft_isdigit.o\
		 ft_isprint.o\
		 ft_itoa.o\
		 ft_memalloc.o\
		 ft_memccpy.o\
		 ft_memchr.o\
		 ft_memcmp.o\
		 ft_memcpy.o\
		 ft_memdel.o\
		 ft_memmove.o\
		 ft_memset.o\
		 ft_putchar.o\
		 ft_putchar_fd.o\
		 ft_putendl.o\
		 ft_putendl_fd.o\
		 ft_putnbr.o\
		 ft_putnbr_fd.o\
		 ft_putstr.o\
		 ft_putstr_fd.o\
		 ft_strcat.o\
		 ft_strchr.o\
		 ft_strclr.o\
		 ft_strcmp.o\
		 ft_strcpy.o\
		 ft_strdel.o\
		 ft_strdup.o\
		 ft_strequ.o\
		 ft_striter.o\
		 ft_striteri.o\
		 ft_strjoin.o\
		 ft_strlcat.o\
		 ft_strlen.o\
		 ft_strmap.o\
		 ft_strmapi.o\
		 ft_strncat.o\
		 ft_strncmp.o\
		 ft_strncpy.o\
		 ft_strnequ.o\
		 ft_strnew.o\
		 ft_strnstr.o\
		 ft_strrchr.o\
		 ft_strsplit.o\
		 ft_strstr.o\
		 ft_strsub.o\
		 ft_strtrim.o\
		 ft_tolower.o\
		 ft_toupper.o\
		 ft_lstnew.o\
		 ft_lstdelone.o\
		 ft_lstdel.o\
		 ft_lstadd.o\
		 ft_lstiter.o\
		 ft_lstmap.o\
		 ft_numlen.o\
		 ft_lstaddnewr.o\
		 ft_lstaddnewl.o\
		 ft_lstaddright.o\
		 ft_power.o\
		 ft_factorial.o\
		 ft_sqrt.o\
		 ft_next_prime.o\
		 ft_factorization.o\
		 ft_isprime.o\
		 ft_convert_base.o
NAME = libft.a
FLAGS = -Wall -Wextra -Werror
INCLUDE_HEADER = -I.

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(INCLUDE_HEADER) -c $(SRC)
	ar rc $(NAME) $(POINTO) && ranlib $(NAME)

clean:
	/bin/rm -f $(POINTO)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
